### ISSUE TITLE
.NET error when opening application in Windows 10

### ISSUE THREAD

**Issue by unicodeixixixi** [IrisV3rm/IrisRobloxMultiTool#3]
![image](https://user-images.githubusercontent.com/109984109/204851264-7d59386f-7b65-4b5d-aa37-e6c438eb92d2.png)
This error is displayed when I open the application; I can't seem to fix it.

When pressing "Continue" you get an empty login screen

**Comment by IrisV3rm** [comment]
Try redownloading 6.0.5 and let me know!

**Comment by unicodeixixixi** [comment]
Seems to work with the new update. Thank you!
